name: Symfony CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: job_board
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 1234
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres" 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 5

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'  # Adjust to your required PHP version
          extensions: mbstring, pdo, pdo_pgsql, xml, intl  # Add any other extensions you need

      - name: Install Composer Dependencies
        run: composer install --no-progress --no-suggest --prefer-dist

      - name: Wait for Database to be Ready
        run: |
          until pg_isready -h localhost -p 5432 -U postgres; do
            echo "Waiting for database..."
            sleep 5
          done

      - name: Run Migrations
        run: php bin/console doctrine:migrations:migrate --no-interaction

      - name: Load Fixtures (if needed)
        run: php bin/console doctrine:fixtures:load --no-interaction

      - name: Run Tests
        run: php bin/console test

      - name: Debug Environment Variables
        run: printenv

      - name: Check Database Connection
        run: |
          php -r "try { new PDO('pgsql:host=127.0.0.1;port=5432;dbname=job_board', 'postgres', '1234'); echo 'Connection successful'; } catch (PDOException $e) { echo 'Connection failed: ' . $e->getMessage(); }"
